name: test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:

env:
  # don't auto-upgrade the gotoolchain
  # https://github.com/docker-library/golang/issues/472
  GOTOOLCHAIN: local

jobs:
  test:
    runs-on: windows-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v5
      -
        name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.24"
      -
        name: Go mod
        run: |
          go mod download
        shell: bash
      -
        name: Test
        run: |
          go test -coverprofile=coverage.txt -covermode=atomic ./...
        shell: bash
      -
        name: Upload coverage
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.txt
          token: ${{ secrets.CODECOV_TOKEN }}
